// <auto-generated />
using System;
using EverolaBlogAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EverolaBlogAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250410090403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EverolaBlogAPI.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Software",
                            Content = "Security testing is a crucial aspect of software development...",
                            CreatedAt = new DateTime(2023, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/blogs/security.jpeg",
                            Title = "How To Tackle Security Testing And Challenges"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Software",
                            Content = "Agile methodology has revolutionized the way we approach testing...",
                            CreatedAt = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/blogs/agile.png",
                            Title = "Agile Testing: It's a new age of testing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
